#!/bin/bash

# colormap

BLACK='\033[0;30m'
DARK_GRAY='\033[1;30m'
BLUE='\033[0;34m'
LIGHT_BLUE='\033[1;34m'
GREEN='\033[0;32m'
LIGHT_GREEN='\033[1;32m'
CYAN='\033[0;36m'
LIGHT_CYAN='\033[1;36m'
RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
PURPLE='\033[0;35m'
LIGHT_PURPLE='\033[1;35m'
BROWN='\033[0;33m'
YELLOW='\033[1;33m'
LIGHT_GRAY='\033[0;37m'
WHITE='\033[1;37m'
NC='\033[0m'

info() {
        echo -e ${GREEN}$*${NC} 
}

warn() {
        echo -e ${YELLOW}$*${NC}
}

gen_password() {
        openssl rand -hex 10
}

get_sources() {
        env_root=$1
        repo_name=$2
        branch=$3
        cd "$env_root/src"
        [ -d ${repo_name} ] || git clone https://github.com/openstack/${repo_name}.git
        cd ${repo_name}
        git checkout "$branch"
        git pull
}

store_auth_info() {
        key=$1
        value=$2

        echo ${value}>${TOP_DIR}/.auth/${key}
}

get_auth_info() {
        key=$1
        if [ -f ${TOP_DIR}/.auth/${key} ]; then
                cat ${TOP_DIR}/.auth/${key}
        else
                value=$(gen_password)
                store_auth_info $key $value
                echo $value
        fi
}

# init environment at path $1
init_environment() {
        mkdir -v ${TOP_DIR}/.auth 2>/dev/null

        env_root=$1
        if [ -f "$env_root/bin/activate" ]; then
                info "Environment exists"
        else
                info "Initializing environment"
                virtualenv -p python2 $env_root
        fi
        mkdir -v "$env_root/log" 2>/dev/null
        mkdir -v "$env_root/src" 2>/dev/null
        mkdir -vp "$env_root/var/lib/glance" 2>/dev/null
        mkdir -v "$env_root/var/lib/glance/images" 2>/dev/null
        mkdir -v "$env_root/var/lib/glance/image-cache" 2>/dev/null
        mkdir -vp "$env_root/var/lib/nova/state" 2>/dev/null
        mkdir -vp "$env_root/var/lock" 2>/dev/null
        mkdir -vp "$env_root/var/www/keystone" 2>/dev/null
        mkdir -vp "$env_root/var/cache/nova" 2>/dev/null
        mkdir -vp "$env_root/data" 2>/dev/null
        #chown -R ${STACK_USER}:${STACK_USER} "$env_root/var/www/keystone"
        #chown -R ${STACK_USER}:${STACK_USER} "$env_root/log"
        #chown -R ${STACK_USER}:${STACK_USER} "$env_root/var/lib/glance"
        #chown -R ${STACK_USER}:${STACK_USER} "$env_root/var/lock"
        info "Entering new environment"
        . "$env_root/bin/activate"
}

# vi: ft=sh
